import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const vazir = localFont({
  src: "./fonts/Vazir.woff2",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Fatemeh Alavi | Personal Portfolio",
  description: "Generated by create next app , Student Front end developer",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={vazir.className}>
      <body className=" max-w-screen-sm mx-auto bg-[#FFF8E8] ">{children}</body>
    </html>
  );
}
